name: LPHK-build
channels:
  - defaults
dependencies:
  - python=3.7*
  - pip
  - tk
  - pip:
    - git+git@github.com:skulblaka24/launchpad.py.git@master
    - pillow
    - pygame
    - pynput
    - tkcolorpicker
    - https://github.com/pyinstaller/pyinstaller/archive/develop.zip
    - py-getch
    - pyautogui
